env               = "dev"
host_os           = "windows"
my_ip             = "1.2.3.4/32"
identityfile_name = "dev_vm"
vpc_cidr_block    = "10.10.0.0/16"
subnet_cidr_block = "10.10.1.0/24"
availability_zone = "ca-central-1a"
ec2_instance_type = "t2.micro"